# +----------------------------------------------------+ #
# <                      Prompts                       > #
# <                   Configuration                    > #
# +----------------------------------------------------+ #





# PlayerUI formatting
# Skull-Name-Format - The display name format
# for the player heads
# Size - the size of the UI (multiple of 9, between 18-54)
# Sorted - Should the player heads be sorted?
# Per-World - Only show player in the current world?
PlayerUI:
  Skull-Name-Format: '&6%s'
  Size: 54
  Previous:
    Item: Feather
    Column: 3
    Text: '&7◀◀ Previous'
  Next:
    Item: Feather
    Column: 7
    Text: Next ▶▶
  Cancel:
    Item: Barrier
    Column: 5
    Text: '&7Cancel ✘'
  Sorted: false
  Per-World: false
  Cache-Size: 256



# AnvilUI formatting
# Enable-Title - Show the first line of the prompt
# (if with {br}) as title of Anvil GUI
# Item - The item to place on the Anvil GUI
# Enchanted - Do you want the item enchanted?
# Custom-Title - If title is enabled, and if custom
# title is not empty, CommandPrompter will use this instead
AnvilGUI:
  Enable-Title: true
  Custom-Title: ''
  Item: Paper
  Enchanted: false



# Text Prompt Config
TextPrompt:
  Clickable-Cancel: false
  Cancel-Message: '&7[&c&l✘&7]'
  Cancel-Hover-Message: '&7Click here to cancel command completion'
  Response-Listener-Priority: DEFAULT


# Sign UI Settings
# Input-Field-Location - Which line should the answer
# be read from.
# Valid Input Field Locations
# top - line 1 of the sign will be considered as the field.
# top-aggregate - the prompt will be placed at the lowest
# possible line and the input would be
# the remaining lines on top.
# bottom - line 4 of the sign will be considered as the
# field.
# bottom-aggregate - the prompt will be placed at line
# 1 and the input would be the
# remaining lines at the bottom
# Check wiki for Sign UI
# https://github.com/CyR1en/CommandPrompter/wiki/Prompts
SignUI:
  Input-Field-Location: bottom
